name: Build and Test

on:
  push:
  pull_request:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build
      run: dotnet build --configuration Release
      working-directory: ./src
  
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Test
      run: dotnet test --blame --configuration Release
      working-directory: ./src
