name: Package Nuget CI

on:
  push:
    tags-ignore:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build
      run: dotnet build --configuration Release
      working-directory: ./src

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Test
      run: dotnet test --blame --configuration Release
      working-directory: ./src
  
  pack:
    runs-on: [ubuntu-latest]
    needs: [build, test]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
      - name: Get Current Version
        uses: Deep-Symmetry/github-version-action@v1
      - name: Create Nuget Package
        shell: bash
        run: dotnet pack -c Release --nologo -o nupkgs /p:Version=$git_version-ci-$GITHUB_RUN_NUMBER
        working-directory: ./src
      - name: Save Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: nupkgs
          path: ./src/nupkgs
