on: push
name: SonarCloud
jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarCloud Scan
      uses: Secbyte/dotnet-sonarscanner@v1.2
      with:
        buildCommand: dotnet build ./src
        testCommand: dotnet test ./src /p:CollectCoverage=true /p:CoverletOutput=../CoverageResults/ /p:MergeWith="../CoverageResults/coverage.json" /p:CoverletOutputFormat="opencover,json" -m:1
        projectKey: Burwin_JsonCryption
        projectName: JsonCryption
        sonarOrganisation: burwin
        beginArguments: /d:sonar.verbose="true" /d:sonar.cs.opencover.reportsPaths="./src/JsonCryption.*.Tests/TestResults/**/coverage.opencover.xml" /d:sonar.coverage.exclusions="**/*.cs"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_V1 }}
