on: push
name: SonarCloud with Coverage
jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build solution
      run: dotnet build ./src
    - name: test solution
      run: dotnet test --collect:"XPlat Code Coverage"
      working-directory: ./src
    - name: install reportgenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    - name: generate solution coverage report
      run: reportgenerator "-reports:**\TestResults\**\coverage.cobertura.xml" "-targetdir:." "-reporttypes:SonarQube"
    - name: save artifacts
      uses: actions/upload-artifact@v1
      with:
        name: debug
        path: .
