name: Test Tag Versions

on:
  push:
    tags: v*-*
  
jobs:
  get_version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: Deep-Symmetry/github-version-action@v1
      with:
        var-name: 'var_name'
        tag-var-name: 'tag_var_name'
        mvn-var-name: 'mvn_var_name'
    - run: |
        echo var_name
        echo tag_var_name
        echo mvn_var_name
